// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Abi2CSharp.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class AbiCodeGen : AbiCodeGenBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// Auto Generated, do not edit.\r\n");
            
            #line 7 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 if (includeEosioModels) { 
            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Globalization;\r\nusing System.IO;\r\nusing Newtonsoft.Js" +
                    "on;\r\nusing AlterMe.Model.eosio;\r\n");
            
            #line 13 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 } 
if (includeEosSharpTest)
{ 
            
            #line default
            #line hidden
            this.Write("using EosSharp;\r\nusing EosSharp.Core;\r\nusing EosSharp.Core.Api.v1;\r\nusing System." +
                    "Net.Http;\r\nusing System.Linq;\r\n");
            
            #line 21 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 } 
            
            #line default
            #line hidden
            this.Write("using System.Collections.Generic;\r\nusing System.Threading.Tasks;\r\n");
            
            #line 24 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"

int lowerBound = (int)'0', upperBound = (int)'9';
Func<string, string, string> getSafeName = (name, prefix) => {
    if (name.StartsWith("Model.eosio.")) return name;
    int firstCharCode = (int)name[0];
    return ((firstCharCode < lowerBound || firstCharCode > upperBound) ? name : $"{prefix}{name}").Replace('.','_');
};

            
            #line default
            #line hidden
            this.Write("namespace AlterMe\r\n{\r\n    public static partial class Contracts\r\n    {    \r\n     " +
                    "   public static class ");
            
            #line 36 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(exportName, "c_")));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            public const string contract = \"");
            
            #line 38 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(contractName));
            
            #line default
            #line hidden
            this.Write("\";\r\n            public static class Actions\r\n            {\r\n");
            
            #line 41 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 foreach (var action in actions) { 
    string name = getSafeName(action.name, "t_");
    if(name == action.name)
    { 
            
            #line default
            #line hidden
            this.Write("                public const string ");
            
            #line 45 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" = nameof(");
            
            #line 45 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 46 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                public const string ");
            
            #line 47 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 47 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.name));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 48 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
  }
} 
            
            #line default
            #line hidden
            this.Write("            }\r\n            public static class Tables\r\n            {\r\n");
            
            #line 53 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 foreach (var table in tables) { 
    string name = getSafeName(table.name, "t_");
    if(name == table.name)
    { 
            
            #line default
            #line hidden
            this.Write("                public const string ");
            
            #line 57 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" = nameof(");
            
            #line 57 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 58 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                public const string ");
            
            #line 59 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 59 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.name));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 60 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
  }
} 
            
            #line default
            #line hidden
            this.Write("            }\r\n            public static class Types\r\n            {\r\n");
            
            #line 65 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 foreach (string i in VariantInterfaces) { 
            
            #line default
            #line hidden
            this.Write("                public interface ");
            
            #line 66 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" { }\r\n");
            
            #line 67 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 } 
            
            #line default
            #line hidden
            
            #line 68 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 foreach (var type in types.Keys) { 
    if (variantUsageLookup.TryGetValue(type, out var interfaces))
    { 
            
            #line default
            #line hidden
            this.Write("                public class ");
            
            #line 71 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(type, "t_")));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 71 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", interfaces)));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 72 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
  }
    else
    { 
            
            #line default
            #line hidden
            this.Write("                public class ");
            
            #line 75 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(type, "t_")));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 76 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
  }
foreach (var field in types[type])
    { 
            
            #line default
            #line hidden
            this.Write("                    public ");
            
            #line 79 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(field.Value, "t_")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 79 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Key));
            
            #line default
            #line hidden
            this.Write("  { get; set; }\r\n");
            
            #line 80 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
  }

            
            #line default
            #line hidden
            this.Write("                }\r\n");
            
            #line 83 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
} 
            
            #line default
            #line hidden
            this.Write("            }\r\n            public static class Requests\r\n            {\r\n");
            
            #line 87 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 foreach (var action in actions) { 
            
            #line default
            #line hidden
            this.Write("                public class ");
            
            #line 88 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(action.name, "t_")));
            
            #line default
            #line hidden
            this.Write(" : Types.");
            
            #line 88 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(action.type, "t_")));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n                }\r\n");
            
            #line 91 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
} 
            
            #line default
            #line hidden
            this.Write("            }\r\n            public static class Responses\r\n            {\r\n");
            
            #line 95 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 foreach (var table in tables) { 
            
            #line default
            #line hidden
            this.Write("                public class ");
            
            #line 96 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(table.name, "t_")));
            
            #line default
            #line hidden
            this.Write(" : Types.");
            
            #line 96 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(table.type, "t_")));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n                }\r\n");
            
            #line 99 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
} 
            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n    }\r\n");
            
            #line 103 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 if (includeExtensions) { 
            
            #line default
            #line hidden
            this.Write("    public static class Extensions\r\n    {\r\n        const char NULL = \'\\0\';\r\n     " +
                    "   const int BitsPerByte = 8;\r\n        const int BytesPer256Bits = 256 / BitsPer" +
                    "Byte;        \r\n        const int Zero = (int)\'0\';\r\n        const int HexAFOffset" +
                    " = 10;\r\n        const int UpperCaseA = (int)\'A\';\r\n        const int UpperCaseAOf" +
                    "fset = UpperCaseA - HexAFOffset;\r\n        const int LowerCaseA = (int)\'a\';\r\n    " +
                    "    const int LowerCaseAOffset = LowerCaseA - HexAFOffset;\r\n        #region Name" +
                    "-based constants\r\n        const int NameMaxCharLength = 13;\r\n        /// <summar" +
                    "y>\r\n        /// The amount of bits an Antelope name is encoded into.\r\n        //" +
                    "/ </summary>\r\n        const int NameBitLength = 64;\r\n        /// <summary>\r\n    " +
                    "    /// The amount of bits we can use per character.\r\n        /// </summary>\r\n  " +
                    "      const int BitsPerNameValue = 5;\r\n        /// <summary>\r\n        /// The am" +
                    "ount of charcters that can use the full bit length we need (12)\r\n        /// </s" +
                    "ummary>\r\n        const int NameFullBitCharCount = NameBitLength / BitsPerNameVal" +
                    "ue;\r\n        /// <summary>\r\n        /// The amount of bits that can have the ful" +
                    "l-length (60 in our case)\r\n        /// </summary>\r\n        const int NameBitsWit" +
                    "hFullBitLength = NameFullBitCharCount * BitsPerNameValue;\r\n        /// <summary>" +
                    "\r\n        /// The amount of bits that remain for the last value (4)\r\n        ///" +
                    " </summary>\r\n        const int NameRestBits = NameBitLength - NameBitsWithFullBi" +
                    "tLength;\r\n        /// <summary>\r\n        /// The last bit index that has <see cr" +
                    "ef=\"BitsPerNameValue\"/> bits per encoded character.\r\n        /// </summary>\r\n   " +
                    "     /// <remarks>\r\n        /// Indexes are 0-based, so we take the amount of bi" +
                    "ts that are full-length values and substract 1.\r\n        /// </remarks>\r\n       " +
                    " const int LastFullLengthNameBitIndex = NameBitsWithFullBitLength - 1;\r\n        " +
                    "/// <summary>\r\n        /// The bitmask we use to extract the bits from the value" +
                    ". We shift by the bit length (e.g. overshoot), \r\n        /// then substract 1 to" +
                    " get a full set of binary 1 flags for our desired bit length.\r\n        /// </sum" +
                    "mary>\r\n        const int NameValueBitMask = (1 << BitsPerNameValue) - 1;\r\n      " +
                    "  /// <summary>\r\n        /// The bitmask we use to extract the bits from the val" +
                    "ue. We shift by the bit length (e.g. overshoot), \r\n        /// then substract 1 " +
                    "to get a full set of binary 1 flags for our desired bit length.\r\n        /// </s" +
                    "ummary>\r\n        const int NameRestBitMask = (1 << NameRestBits) - 1;\r\n        #" +
                    "endregion\r\n        static Dictionary<char, byte> CharByteLookup;\r\n        static" +
                    " Dictionary<byte, char> ByteCharLookup;\r\n        static Extensions()\r\n        {\r" +
                    "\n            CharByteLookup = new Dictionary<char, byte>();\r\n            ByteCha" +
                    "rLookup = new Dictionary<byte, char>();\r\n            CharByteLookup.Add(\'.\', 0);" +
                    "\r\n            ByteCharLookup.Add(0, \'.\');\r\n            for (byte i = 1; i <= 5; " +
                    "++i)\r\n            {\r\n                CharByteLookup.Add(i.ToString()[0], i);\r\n  " +
                    "              ByteCharLookup.Add(i, i.ToString()[0]);\r\n            }\r\n          " +
                    "  byte offset = \'a\' - 6;\r\n            for (char c = \'a\'; c <= \'z\'; ++c)\r\n       " +
                    "     {\r\n                CharByteLookup.Add(c, (byte)((byte)c - offset));\r\n      " +
                    "          ByteCharLookup.Add((byte)((byte)c - offset), c);\r\n            }\r\n     " +
                    "   }\r\n        public static string ReadEosioString(this BinaryReader br) => Syst" +
                    "em.Text.Encoding.UTF8.GetString(br.ReadBytes(br.DecodeInt32()));\r\n        public" +
                    " static string ToName(this ulong value)\r\n        {\r\n            char[] result = " +
                    "new char[NameMaxCharLength];\r\n            byte v;\r\n            char c;\r\n        " +
                    "    int resultIndex = 0;\r\n            // The first 60 bits are 5-bits per value;" +
                    " \r\n            for (int i = 0; i < NameBitsWithFullBitLength; i += BitsPerNameVa" +
                    "lue)\r\n            {\r\n                v = (byte)((value >> LastFullLengthNameBitI" +
                    "ndex - i) & NameValueBitMask);\r\n                c = ByteCharLookup[v];\r\n        " +
                    "        result[resultIndex++] = c;\r\n            }\r\n            v = (byte)(value " +
                    "& NameRestBitMask);\r\n            c = ByteCharLookup[v];\r\n            result[resu" +
                    "ltIndex] = c;\r\n            // Strip any trailing 0-values (e.g. \'.\')\r\n          " +
                    "  return new string(result).TrimEnd(ByteCharLookup[0]);\r\n        }\r\n        publ" +
                    "ic static ulong NameToLong(this string name)\r\n        {\r\n            ulong resul" +
                    "t = 0L;\r\n            int bitIndex = 0, i;\r\n            byte c;\r\n            // P" +
                    "rocess the full-bit-length characters\r\n            for (i = 0; i < NameFullBitCh" +
                    "arCount; i++)\r\n            {\r\n                c = i < name.Length ? CharByteLook" +
                    "up[name[i]] : (byte)0;\r\n                if ((c & 0b00001) == 0b00001) result += " +
                    "1UL << (59 - bitIndex);\r\n                if ((c & 0b00010) == 0b00010) result +=" +
                    " 1UL << (60 - bitIndex);\r\n                if ((c & 0b00100) == 0b00100) result +" +
                    "= 1UL << (61 - bitIndex);\r\n                if ((c & 0b01000) == 0b01000) result " +
                    "+= 1UL << (62 - bitIndex);\r\n                if ((c & 0b10000) == 0b10000) result" +
                    " += 1UL << (63 - bitIndex);\r\n                bitIndex += 5;\r\n            }\r\n    " +
                    "        // Process the last 4 bits\r\n            c = i < name.Length ? CharByteLo" +
                    "okup[name[i]] : (byte)0;\r\n            if ((c & 0b0001) == 0b0001) result += 1UL;" +
                    "\r\n            if ((c & 0b0010) == 0b0010) result += 1UL << 1;\r\n            if ((" +
                    "c & 0b0100) == 0b0100) result += 1UL << 2;\r\n            if ((c & 0b1000) == 0b10" +
                    "00) result += 1UL << 3;\r\n            return result;\r\n        }\r\n        public s" +
                    "tatic int GetHexVal(this char hex)\r\n        {\r\n            int val = (int)hex;\r\n" +
                    "            if (val < UpperCaseA)\r\n                return val - Zero;\r\n         " +
                    "   else if (val < LowerCaseA)\r\n                return val - UpperCaseAOffset;\r\n " +
                    "           return\r\n                val - LowerCaseAOffset;\r\n        }\r\n        p" +
                    "ublic static byte[] ToByteArrayFastest(this string hex)\r\n        {\r\n            " +
                    "if (hex.Length % 2 == 1)\r\n                throw new Exception(\"The binary key ca" +
                    "nnot have an odd number of digits\");\r\n            int byteCount = hex.Length >> " +
                    "1;\r\n\r\n            byte[] arr = new byte[byteCount];\r\n\r\n            for (int i = " +
                    "0; i < byteCount; ++i)\r\n            {\r\n                arr[i] = (byte)((hex[i <<" +
                    " 1].GetHexVal() << 4) + hex[(i << 1) + 1].GetHexVal());\r\n            }\r\n\r\n      " +
                    "      return arr;\r\n        }\r\n        public static string ToHexUpper(this byte[" +
                    "] value)\r\n        {\r\n            char[] result = new char[value.Length * 2];\r\n  " +
                    "          int index = 0;\r\n            byte b;\r\n            for (int ix = 0; ix <" +
                    " result.Length; ix += 2)\r\n            {\r\n                b = value[index++];\r\n  " +
                    "              result[ix] = GetHexUpper(b / 16);\r\n                result[ix + 1] " +
                    "= GetHexUpper(b % 16);\r\n            }\r\n            return new string(result);\r\n " +
                    "       }\r\n        public static string ToHexLower(this byte[] value)\r\n        {\r" +
                    "\n            char[] result = new char[value.Length * 2];\r\n            int index " +
                    "= 0;\r\n            byte b;\r\n            for (int ix = 0; ix < result.Length; ix +" +
                    "= 2)\r\n            {\r\n                b = value[index++];\r\n                result" +
                    "[ix] = GetHexLower(b / 16);\r\n                result[ix + 1] = GetHexLower(b % 16" +
                    ");\r\n            }\r\n            return new string(result);\r\n        }\r\n        st" +
                    "atic char GetHexUpper(int i)\r\n        {\r\n            if (i < 0 || i > 15) throw " +
                    "new ArgumentException(\"Value must be between 0 and 15\");\r\n            else if (i" +
                    " < 10) return (char)(i + \'0\');\r\n            return (char)(i - 10 + \'A\');\r\n      " +
                    "  }\r\n        static char GetHexLower(int i)\r\n        {\r\n            if (i < 0 ||" +
                    " i > 15) throw new ArgumentException(\"Value must be between 0 and 15\");\r\n       " +
                    "     else if (i < 10) return (char)(i + \'0\');\r\n            return (char)(i - 10 " +
                    "+ \'a\');\r\n        }\r\n    }\r\n    public static class VariableLengthInteger\r\n    {\r" +
                    "\n        const int BitsPerByte = 8;\r\n        const int DataBits = BitsPerByte - " +
                    "1;\r\n        const int DataBitMask = (1 << DataBits) - 1;\r\n        const int Cont" +
                    "inuationBit = 1 << DataBits;\r\n        public static void EncodeInt32(this Binary" +
                    "Writer writer, int value)\r\n        {\r\n            if (writer == null)\r\n         " +
                    "       throw new ArgumentNullException(nameof(writer));\r\n            if (value <" +
                    " 0)\r\n                throw new ArgumentOutOfRangeException(nameof(value), value," +
                    " $\"{nameof(value)} must be 0 or greater\");\r\n            foreach(byte val in valu" +
                    "e.EncodeInt32())\r\n                writer.Write(val);\r\n        }\r\n        public " +
                    "static IEnumerable<byte> EncodeInt32(this uint value)\r\n        {\r\n            do" +
                    "\r\n            {\r\n                // Grab the lowest 7-bits of the value\r\n       " +
                    "         byte lower7bits = (byte)(value & DataBitMask);\r\n                // Then" +
                    " shift the value by 7 and check if there is any value left.\r\n                val" +
                    "ue >>= DataBits;\r\n                if (value > 0) // If anything remains, ensure " +
                    "the continuation bit is set by OR-ing with 10000000 (1 + 7 bits from the data)\r\n" +
                    "                    lower7bits |= ContinuationBit;\r\n                yield return" +
                    " lower7bits;\r\n            } while (value > 0);\r\n        }\r\n        public static" +
                    " IEnumerable<byte> EncodeInt32(this int value)\r\n        {\r\n            if (value" +
                    " < 0) throw new ArgumentOutOfRangeException(nameof(value), value, $\"{nameof(valu" +
                    "e)} must be 0 or greater\");\r\n            foreach(var b in EncodeInt32((uint)valu" +
                    "e)) \r\n                yield return b;\r\n        }\r\n        public static int Deco" +
                    "deInt32(this BinaryReader reader)\r\n        {\r\n            if (reader == null) th" +
                    "row new ArgumentNullException(nameof(reader));\r\n            bool more = true;\r\n " +
                    "           int value = 0, shift = 0;\r\n            while (more)\r\n            {\r\n " +
                    "               byte lower7bits = reader.ReadByte();\r\n                more = (low" +
                    "er7bits & ContinuationBit) != 0;\r\n                value |= (lower7bits & DataBit" +
                    "Mask) << shift;\r\n                shift += DataBits;\r\n            }\r\n            " +
                    "return value;\r\n        }\r\n        public static int DecodeInt32(this IEnumerable" +
                    "<byte> bytes, bool breakOnNoMore = false)\r\n        {\r\n            if (bytes == n" +
                    "ull) throw new ArgumentNullException(nameof(bytes));\r\n            bool more = tr" +
                    "ue;\r\n            int value = 0, shift = 0;\r\n            foreach(byte lower7bits " +
                    "in bytes)\r\n            {\r\n                more = (lower7bits & ContinuationBit) " +
                    "!= 0;\r\n                value |= (lower7bits & DataBitMask) << shift;\r\n          " +
                    "      shift += DataBits;\r\n                if (breakOnNoMore && !more) break;\r\n  " +
                    "          }\r\n            if (more) throw new ArgumentException(\"Last byte still " +
                    "had the \'more\' flag set!\", nameof(bytes));\r\n            return value;\r\n        }" +
                    "\r\n        public static int DecodeInt32(this MemoryStream ms)\r\n        {\r\n      " +
                    "      if (ms == null) throw new ArgumentNullException(nameof(ms));\r\n            " +
                    "bool more = true;\r\n            int value = 0, shift = 0;\r\n            while (mor" +
                    "e)\r\n            {\r\n                byte lower7bits = (byte)ms.ReadByte();\r\n     " +
                    "           more = (lower7bits & ContinuationBit) != 0;\r\n                value |=" +
                    " (lower7bits & DataBitMask) << shift;\r\n                shift += DataBits;\r\n     " +
                    "       }\r\n            return value;\r\n        }\r\n    }    \r\n    public class Cust" +
                    "omJsonConverter<T>\r\n        : JsonConverter\r\n        where T : ICustomSerialize<" +
                    "T>\r\n    {\r\n        public override bool CanConvert(Type objectType) => true;\r\n  " +
                    "      public override void WriteJson(JsonWriter writer, object value, JsonSerial" +
                    "izer serializer)\r\n        {\r\n            if (value is ICustomSerialize<T> t) wri" +
                    "ter.WriteValue(t.Serialize());\r\n        }\r\n        public override bool CanRead " +
                    "{ get => true; }\r\n        public override object ReadJson(JsonReader reader, Typ" +
                    "e objectType, object existingValue, JsonSerializer serializer)\r\n        {\r\n     " +
                    "       if (existingValue is ICustomSerialize<T> t) return t.Deserialize(reader);" +
                    "\r\n            return null;\r\n        }\r\n    }\r\n");
            
            #line 377 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 }
            
            #line default
            #line hidden
            
            #line 378 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 if (includeEosioModels) { 
            
            #line default
            #line hidden
            this.Write("\tnamespace Model.eosio\r\n\t{\r\n        public interface ICustomSerialize<T>\r\n       " +
                    " {\r\n            string Serialize();\r\n            T Deserialize(JsonReader reader" +
                    ");\r\n        }\r\n        [JsonConverter(typeof(CustomJsonConverter<Asset>))]\r\n\t   " +
                    " public class Asset : ICustomSerialize<Asset>\r\n\t\t{\r\n\t\t\tconst string EnglishCultu" +
                    "reName = \"en-GB\";\r\n\t\t\tstatic readonly CultureInfo EnglishCulture = new CultureIn" +
                    "fo(EnglishCultureName);\r\n\t\t\tpublic Symbol Token { get; set; }\r\n\t\t\tpublic UInt64 " +
                    "Balance { get; set; }\r\n\t\t\t[JsonIgnore]\r\n\t\t\tpublic decimal BalanceDecimal { get =" +
                    "> Balance / (decimal)Token.Factor; set => Balance = (ulong)(value * (decimal)Tok" +
                    "en.Factor); }\r\n\t\t\t/// <remarks>\r\n\t\t\t/// We use the F string format so there is o" +
                    "nly a decimal, no thousand separator.\r\n\t\t\t/// </remarks>\r\n\t\t\tpublic override str" +
                    "ing ToString() => $\"{BalanceDecimal.ToString($\"F{Token.precision}\", EnglishCultu" +
                    "re)} {Token.name}\";\r\n\t\t\tpublic Asset() { } // Empty constructor for serializing\r" +
                    "\n\t\t\tpublic static implicit operator Asset(string value)\r\n\t\t\t{\r\n\t\t\t\tAsset result " +
                    "= new Asset();\r\n\t\t\t\tstring[] parts = value.Split(\' \');\r\n\t\t\t\tif (parts.Length != " +
                    "2) throw new ArgumentException($\"Cannot parse \'{value}\' as a valid token balance" +
                    "\", nameof(value));\r\n\t\t\t\tstring[] valueParts = parts[0].Split(\'.\');\r\n\t\t\t\tresult.T" +
                    "oken = new Symbol(\r\n\t\t\t\t\tname: parts[1], \r\n\t\t\t\t\tprecision: (byte)(valueParts.Len" +
                    "gth == 2 ? valueParts[1].Length : 0)\r\n\t\t\t\t);\r\n\t\t\t\tif (decimal.TryParse(parts[0]," +
                    " NumberStyles.AllowDecimalPoint, EnglishCulture, out decimal balance)) result.Ba" +
                    "lanceDecimal = balance;\r\n\t\t\t\telse throw new ArgumentException($\"Unable to parse " +
                    "\'{parts[0]}\' as a valid decimal\");\r\n\t\t\t\treturn result;\r\n\t\t\t}\r\n\t\t    public stati" +
                    "c implicit operator string(Asset value) => value.ToString();\r\n\t\t    public strin" +
                    "g Serialize() => ToString();\r\n\t\t    public Asset Deserialize(JsonReader reader) " +
                    "=> reader.ReadAsString();\r\n\t\t}\r\n        [JsonConverter(typeof(CustomJsonConverte" +
                    "r<Name>))]\r\n        public class Name : ICustomSerialize<Name>\r\n        {\r\n     " +
                    "       ulong _Value;\r\n            string _Name;\r\n            public ulong Value " +
                    "\r\n            { \r\n                get => _Value; \r\n                set \r\n       " +
                    "         {\r\n                    if(value != _Value)\r\n                    {\r\n    " +
                    "                    _Value = value;\r\n                        _Name = value.ToNam" +
                    "e();\r\n                    }\r\n                } \r\n            }\r\n            publ" +
                    "ic string AsString { \r\n                get => _Name;\r\n                set\r\n     " +
                    "           {\r\n                    if(value != _Name)\r\n                    {\r\n   " +
                    "                     _Name = value;\r\n                        _Value = AsString.N" +
                    "ameToLong();\r\n                    }\r\n                }\r\n            }\r\n         " +
                    "   public Name(string value)\r\n            {\r\n                AsString = value;\r\n" +
                    "            }\r\n            public Name(ulong value)\r\n            {\r\n            " +
                    "    Value = value;\r\n            }\r\n            public static implicit operator u" +
                    "long(Name value) => value.Value;\r\n            public static implicit operator st" +
                    "ring (Name value) => value.AsString;\r\n            public static implicit operato" +
                    "r Name(ulong value) => new Name(value);\r\n            public static implicit oper" +
                    "ator Name(string value) => new Name(value);\r\n            public override string " +
                    "ToString() => AsString;\r\n            public string Serialize() => AsString;\r\n   " +
                    "         public Name Deserialize(JsonReader reader) => reader.ReadAsString();\r\n " +
                    "       }\r\n\t    [JsonConverter(typeof(CustomJsonConverter<Symbol>))]\r\n\t    public" +
                    " class Symbol : ICustomSerialize<Symbol>\r\n        {\r\n\t        const char Separat" +
                    "or = \',\';\r\n\t        const int FixedNameByteLength = 7;\r\n            public byte " +
                    "precision { get; set; }\r\n            public string name { get; set; }\r\n\t        " +
                    "/// <remarks>\r\n\t        /// <see cref=\"System.Math.Pow\">System.Math.Pow(10, 0)</" +
                    "see> returns 1, \r\n\t        /// otherwise, this should have been written with a <" +
                    "see cref=\"System.Math.Max\"/>\r\n\t        /// </remarks>\r\n\t        [JsonIgnore]\r\n\t " +
                    "       public double Factor { get => System.Math.Pow(10, precision); }\r\n\t       " +
                    " public Symbol() { }\r\n\t        public Symbol(string name, byte precision) {\r\n\t\t " +
                    "       this.name = name;\r\n\t\t        this.precision = precision;\r\n\t        }\r\n\t  " +
                    "      public static implicit operator Symbol(string value)\r\n            {\r\n\t\t   " +
                    "     string[] parts = value.Split(Separator);\r\n\t\t        if (parts.Length != 2) " +
                    "throw new System.ArgumentException($\"Symbol should be precision, followed by nam" +
                    "e, separated by \'{Separator}\'\", nameof(value));\r\n\t\t        else if (!byte.TryPar" +
                    "se(parts[0], out byte precision)) throw new System.ArgumentException($\"Can\'t par" +
                    "se \'{parts[0]}\' as precision\", nameof(value));\r\n\t\t        else return new Symbol" +
                    "(parts[1], precision);\r\n\t        }\r\n\t\t    public static implicit operator string" +
                    "(Symbol value) => value.ToString();\r\n\t        public override string ToString() " +
                    "=> $\"{precision}{Separator}{name}\";\r\n\t\t    public string Serialize() => ToString" +
                    "();\r\n\t\t    public Symbol Deserialize(JsonReader reader) => reader.ReadAsString()" +
                    ";\r\n        }\r\n        [JsonConverter(typeof(CustomJsonConverter<CheckSum256>))]\r" +
                    "\n        public class CheckSum256 : ICustomSerialize<CheckSum256>\r\n        {\r\n  " +
                    "          const int BitsPerByte = 8;\r\n            const int ExpectedLength = 256" +
                    " / BitsPerByte;\r\n            byte[] _Raw;\r\n            string _AsString;\r\n      " +
                    "      public byte[] Raw\r\n            {\r\n                get => _Raw;\r\n          " +
                    "      set\r\n                {\r\n                    _Raw = value;\r\n               " +
                    "     _AsString = value.ToHexLower();\r\n                }\r\n            }\r\n        " +
                    "    public string AsString\r\n            {\r\n                get => _AsString;\r\n  " +
                    "              set\r\n                {\r\n                    _AsString = value;\r\n  " +
                    "                  _Raw = value.ToByteArrayFastest();\r\n                }\r\n       " +
                    "     }\r\n            public CheckSum256(string value)\r\n            {\r\n           " +
                    "     AsString = value;\r\n            }\r\n            public static implicit operat" +
                    "or CheckSum256(string value)\r\n            {\r\n                int valueLength = v" +
                    "alue?.Length ?? 0;\r\n                if (valueLength != ExpectedLength) throw new" +
                    " System.ArgumentException($\"A {nameof(CheckSum256)} should be {ExpectedLength} b" +
                    "ytes in length. Supplied value byte length: {valueLength}\", nameof(value));\r\n   " +
                    "             else return new CheckSum256(value);\r\n            }\r\n            pub" +
                    "lic static implicit operator string(CheckSum256 value) => value.AsString;\r\n     " +
                    "       public override string ToString() => AsString;\r\n            public string" +
                    " Serialize() => AsString;\r\n            public CheckSum256 Deserialize(JsonReader" +
                    " reader) => reader.ReadAsString();\r\n        }\r\n\t} \r\n");
            
            #line 533 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 }
if (includeEosSharpTest)
{ 
            
            #line default
            #line hidden
            this.Write("    public static class Test\r\n    {\r\n        public static async Task Run()\r\n    " +
                    "    {\r\n            var api = new EosApi(new EosConfigurator()\r\n            {\r\n  " +
                    "              SignProvider = null,\r\n                HttpEndpoint = \"");
            
            #line 543 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(api));
            
            #line default
            #line hidden
            this.Write("\",\r\n                ChainId = \"");
            
            #line 544 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(chainId));
            
            #line default
            #line hidden
            this.Write("\"\r\n            }, new HttpHandler());\r\n            var result = await api.GetTabl" +
                    "eRows<Contracts.");
            
            #line 546 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(exportName, "c_")));
            
            #line default
            #line hidden
            this.Write(".Responses.");
            
            #line 546 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(tables[0].name, "c_")));
            
            #line default
            #line hidden
            this.Write(">(new GetTableRowsRequest()\r\n            {\r\n                json = true,\r\n       " +
                    "         code = Contracts.");
            
            #line 549 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(exportName, "c_")));
            
            #line default
            #line hidden
            this.Write(".contract,\r\n                scope = Contracts.");
            
            #line 550 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(exportName, "c_")));
            
            #line default
            #line hidden
            this.Write(".contract,\r\n                table = Contracts.");
            
            #line 551 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(exportName, "c_")));
            
            #line default
            #line hidden
            this.Write(".Tables.");
            
            #line 551 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSafeName(tables[0].name, "c_")));
            
            #line default
            #line hidden
            this.Write(",\r\n                reverse = false,\r\n                show_payer = false,\r\n       " +
                    "     });\r\n            Console.WriteLine(JsonConvert.SerializeObject(result.rows." +
                    "FirstOrDefault()));\r\n        }\r\n    }\r\n");
            
            #line 558 "D:\github\ABI2CSharp\Templates\AbiCodeGen.tt"
 }

            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class AbiCodeGenBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
